name: 'Vault Action'
author: 'Bjerk AS'
description: 'Export secrets from Vault into Github Actions'
branding:
  icon: bookmark
  color: gray-dark
inputs:
    endpoint:
        description: 'Vault Endpoint'
        required: true
    path:
        description: 'Path to secret from Vault'
        required: true
    authMethod:
        description: 'Type of authentication method'
        required: true
    token:
        description: 'Vault Token'
        required: false
    githubToken:
        description: 'Github Token'
        required: true
outputs:
    secret:
        description: 'The output from secret'
runs:
    using: 'node12'
    main: 'dist/index.js'
